#+TITLE: Correction TD Noyaux & Particules
#+AUTHOR: Xavier Garrido
#+DATE: 25/11/13
#+OPTIONS: ^:{}
#+LATEX_CLASS: snemo-note
#+LATEX_HEADER: \renewcommand{\contentsname}{}
#+LATEX_HEADER: \newcommand{\vv}[1]{\overrightarrow{#1}}
#+LATEX: \newpage

* TD1 : Cinématique & Accélérateurs
** Introduction

#+BEGIN_CENTER
Noyau :\nbsp^{A}_{Z}X \rightarrow Z protons  + N neutrons = A nucléons (nombre de masse)
#+END_CENTER

- Noyau ayant le même nombre de protons Z sont appelés des *isotopes* tandis que
  ceux présentant le même nombre de nucléons A sont des *isobares*

- Noyau \equiv objet quantique
  - une fonction d'onde décrit les propriétés du noyau
  - les nombres quantiques associés : spin, parité, isospin
  - il possède un état fondamental et des états excités
  - chaque état possède un moment électronique et un moment magnétique

Certains noyaux sont stables, d'autres radioactifs se désintégrant spontanément

$$^{14}_{6}C \rightarrow\nbsp^{14}_{7}N + e^{-} + \bar{\nu}_{e}$$

Pour étudier le noyau, on forme des réactions nucléaires qui obéissent à des
lois de conservation (charge, nombre de nucléons, parité...). On bombarde une
cible avec \neq projectiles (\gamma, e^{-}, n, p, ions lourds), à \neq
énergies. Ces réactions sont possibles avec \neq probabilités (section
efficace). On peut étudier chaque réaction dont les états finaux peuvent
différer et déterminer la variation de la section efficace en fonction de
l'énergie incident (fonction d'excitation) ou en fonction de l'angle de sortie
(distribution angulaire).

*Rayon des noyaux :* En 1909, Hans Geiger et Ernest Marsden sous la direction
d'Ernest Rutherford, mettent en évidence le noyau atomique en étudiant la
diffusion de particules \alpha sur des atomes d'or (Au). Antérieurement à cette
expérience, la matière était conçue sous la forme d'atome contenant deux parties
chargées électriquement de façons opposées. L'expérience de Rutherford montra
qu'en réalité le noyau chargé positivement est de taille très petite devant le
nuage électronique qui l'entoure, chargé négativement.

En supposant que le noyau soit une sphère uniformément chargée en volume et
contenant A nucléons

$$V = \frac{4}{3}\pi\,R^{3} \propto A$$

On déduit que la rayon d'un noyau est proportionnel à son nombre de nucléons
*R = r_{0} \times A^{1/3}*. Expérimentalement, r_{0} est compris entre 1.2 et 1.5
fermi où 1 fm = 10^{-15} m = 10^{-13} cm. La valeur la plus probable est r_{0} =
1.25 fm.

** Ordres de grandeurs
- Volume du noyau de\nbsp^{12}_{6}C : approx. sphérique

#+BEGIN_SRC latex
    \begin{align*}
      V = \frac{4}{3}\pi\,R^{3} &= \frac{4}{3}\pi\,(r_{0}\,A^{1/3}) \\
      V(^{12}_{6}C)&= \frac{4}{3}\pi\,(1.25\times12^{1/3}) \\
      &\simeq 100\,fm^3 = 10^{-37}\, cm^3
    \end{align*}
#+END_SRC

- Masse volumique
  \nbsp^{12}_{6}C \rightarrow noyau particulier à partir duquel est défini
  l'unité de masse atomique

$$1\,u.m.a = \frac{masse(^{12}_{6}C)}{12} = 931.5\,MeV/c^{2}$$

d'où

#+BEGIN_SRC latex
  \begin{align*}
    m(^{12}_{6}C)c^2 &= 12\times931.5\,MeV = 12\times931.5\times1.6\,10^{-19}\,J \\
    m(^{12}_{6}C)    &= \frac{12\times931.5\times1.6\,10^{-19}}{(3\,10^8)^2} = 2\,10^{-26}\,kg = 2\,10^{-23}\,g\\
  \end{align*}
#+END_SRC

On en déduite que la masse volumique est égale à

$$\rho(^{12}_{6}C) = \frac{m(^{12}_{6}C)}{V(^{12}_{6}C)} =
\frac{2\,10^{-23}}{10^{-37}} = 2\,10^{14} g/cm^3$$

À titre de comparaison, le bois a une densité moyenne de 0.6 -- 1 g/cm^{3}, le
fer environ 10 g/cm^{3}, la Terre de 6 g/cm^{3} et l'Uranium de 19 g/cm^{3}.

*Remarques :* la densité au sein d'une étoile à neutrons est voisine de 10^{11} g/cm^{3}

** Cinématique

Désintégration en deux photons : a \rightarrow \gamma_{1} + \gamma_{2}, énergie
de a au repos mc^{2} et vitesse de a \beta=v/c

1) dans $\mathcal{R^\prime}$ /i.e./ le référentiel du centre de masse où a est
   au repos et $\Upsigma\vv{p}^{*} = \vv{0}$ :

   *\rightarrow Conservation de l'énergie totale :*
   #+BEGIN_SRC latex
     \begin{align*}
       E_{a}^* &= E_1^* + E_2^*\\
       mc^2 &= E_1^* + E_2^*
     \end{align*}
   #+END_SRC

   *\rightarrow Conservation de l'impulsion :*
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{p_a}^* &= \vv{p_1}^* + \vv{p_2}^* \\
       \vv{0} &= \vv{p_1}^* + \vv{p_2}^* \\
       \|\vv{p_1}^*\| &= \|\vv{p_2}^*\|
     \end{align*}
   #+END_SRC

   or E_{1}^{*} = p_{1}^{*}c et E_{2}^{*} = p_{2}^{*}c d'où E_{1}^{*} =
   E_{2}^{*} = $\frac{mc^{2}}{2}$.

   Pour déterminer les valeurs d'énergie et d'impulsion dans le référentiel du
   laboratoire \(\mathcal{R}\), on applique la transformation de Lorentz le long
   de l'axe z au quadrivecteur énergie -- impulsion

   #+BEGIN_SRC latex
     \begin{equation*}
       \begin{bmatrix}
         E\\p_xc\\p_yc\\p_zc
       \end{bmatrix}
       =
       \begin{bmatrix}
         \gamma&0&0&\beta\gamma\\
         0&1&0&0\\
         0&0&1&0\\
         \beta\gamma&0&0&\gamma
       \end{bmatrix}
       \cdot
       \begin{bmatrix}
         E^*\\p_x^*c\\p_y^*c\\p_z^*c
       \end{bmatrix}
     \end{equation*}
   #+END_SRC

   #+BEGIN_SRC latex
     \begin{align*}
       E_1 &= \gamma\,E_1^* + \beta\gamma\,p_{1z}^*c = \gamma\,(mc^2/2 + \beta c\,p_{1z}^*)\\
       E_2 &= \gamma\,E_2^* + \beta\gamma\,p_{2z}^*c = \gamma\,(mc^2/2 + \beta c\,p_{2z}^*)
     \end{align*}
   #+END_SRC
   et
   #+BEGIN_SRC latex
     \begin{align*}
       p_{1z}^* &= p_{1}^*\,\cos\theta^* = +\frac{mc}{2}\,\cos\theta^*\\
       p_{2z}^* &= p_{2}^*\,\cos\theta^* = -\frac{mc}{2}\,\cos\theta^*
     \end{align*}
   #+END_SRC
   soit
   #+BEGIN_SRC latex
     \begin{align*}
       E_1 &= \frac{\gamma\,mc^2}{2}(1 + \beta\cos\theta^*) \\
       E_2 &= \frac{\gamma\,mc^2}{2}(1 - \beta\cos\theta^*)
     \end{align*}
   #+END_SRC

   L'énergie minimum E_{min} et maximum E_{max} sont les mêmes pour E_{1} et
   E_{2} avec cos \theta^{*} \in [-1;1] /i.e./
   #+BEGIN_SRC latex
     \begin{align*}
       E_{min} &= \frac{\gamma\,mc^2}{2}(1 - \beta) = \frac{mc^2}{2}\sqrt{\frac{1-\beta}{1+\beta}}\\
       E_{max} &= \frac{\gamma\,mc^2}{2}(1 + \beta) = \frac{mc^2}{2}\sqrt{\frac{1+\beta}{1-\beta}}
     \end{align*}
   #+END_SRC
   où $\gamma=1/\sqrt{1-\beta^{2}}$.

2) Angle d'ouverture \omega en fonction de \theta^{*}

   Invariant relativiste $I = (\Upsigma_{i}E_{i})^{2} -
   (\Upsigma_{i}\vv{p_{i}}^{*})^{2}\,c^{2}$ constant quelque soit le
   référentiel \rightarrow *I_{cdm} = I_{lab.}*

   #+BEGIN_SRC latex
     \begin{align*}
       (E_1^* + E_2^*)^2 - \vv{0} &= (E_1 + E_2)^2 - (\vv{p_1}c + \vv{p_2}c)^2 \\
       (mc^2)^2 &= E_1^2 + E_2^2 + 2E_1E_2 - (p_1c)^2 - (p_2c)^2 - 2p_1p_2c^2\,\cos\omega
     \end{align*}
   #+END_SRC
   or E_{1} = p_{1}c et E_{2} = p_{2}c d'où
   #+BEGIN_SRC latex
     \begin{align*}
       \frac{(mc^2)^2}{2} &= E_1E_2 - p_1p_2c^2\,\cos\omega\\
       \frac{(mc^2)^2}{2} &= E_1E_2\cdot(1 - \cos\omega)
     \end{align*}
   #+END_SRC
   En remplaçant E_{1,2} par leurs expressions déduites de la question 1), on a
   $E_{1}E_{2} = \left(\frac{\gamma\,mc^2}{2}\right)^2\cdot\left(1 -
   \beta^2\cos^2\theta^*\right)$, soit finalement

   $$1 - \cos\omega = \frac{2}{\gamma^2\,(1 - \beta^2\cos^2\theta^*)}$$

** Énergie seuil

#+BEGIN_CENTER
Réaction : a + b \rightarrow c + d + e + f
#+END_CENTER

Par définition, l'énergie seuil est l'énergie *juste nécessaire* à la création
des particules en voie de sortie sans que ces dernières n'aient d'impulsion
/i.e./ d'énergie cinétique.

1) Dans le référentiel du centre de masse, on applique la conservation de
   l'énergie totale sachant que les particules produites sont au repos /i.e./
   $\vv{p_c}^* = \vv{p_d}^* = \vv{p_e}^* =
   \vv{p_f}^* = \vv{0}$. Par ailleurs,
   $\vv{p_a}^* = -\vv{p_b}^*$ donc T_{a} = T_{b} =
   T_{S} et étant donné que m_{a} = m_{b}, l'énergie totale de la particule a
   est égale à celle de la particule b. En appliquant le principe de
   conservation de l'énergie totale, on obtient

   #+BEGIN_SRC latex
     \begin{align*}
       E_a^* + E_b^* &= m_cc^2 + m_dc^2 + m_ec^2 + m_fc^2 = \Upsigma m_{finale}c^2\\
       2T_S + 2mc^2 &= \Upsigma m_{finale}c^2
     \end{align*}
   #+END_SRC

   soit

   $$T_{S} = \frac{\Upsigma m_{finale}c^2 - \Upsigma m_{initiale}c^2}{2}$$

   En définissant Q comme la chaleur de réaction /i.e./ l'énergie disponible
   dans la réaction où Q = \Upsigma m_{initiale}c^{2} - \Upsigma m_{finale}c^{2}
   et T_{S} = |Q|/2, on distingue 3 situations :

   - Q > 0 :: la réaction est éxoénergétique c'est-à-dire spontanée. Dans ce cas,
              il n'y a pas d'énergie seuil, la réaction se faisant d'elle même,
   - Q < 0 :: la réaction est dite endoénergétique et n'est envisageable qu'à la
              condition de fournir de l'énergie (cinétique) en voie d'entrée.

2) Réaction dans le référentiel du laboratoire : soit un faisceau de particule a
   envoyé sur une cible fixe constituée de particule b \rightarrow
   $\vv{p_b} = \vv{0}$. L'énergie seuil est la valeur
   minimale de T_{a} suffisant à la création des particules c, d, e, f au
   repos. L'invariant relativiste I est égal à
   #+BEGIN_SRC latex
     \begin{align*}
       I_{lab.} = \left(\Upsigma m_{finale}c^2\right)^2 &= \left(\Upsigma E\right)^2 - \left(\Upsigma pc\right)^2\\
       &= (T_S + m_ac^2 + m_bc^2)^2 - (p_ac)^2\\
       &= (T_S + \Upsigma m_{initiale}c^2)^2 - (p_ac)^2
     \end{align*}
   #+END_SRC

   or E^{2} = p^{2}c^{2} + m^{2}c^{4} = (T + mc^{2})^{2} \rightarrow (pc)^{2} =
   T^{2} + 2Tmc^{2}. On déduit ainsi l'expression de I_{lab.}
   #+BEGIN_SRC latex
     \begin{align*}
       I_{lab.} = \left(\Upsigma m_{finale}c^2\right)^2 &= T_S^2 + 2T_S\Upsigma m_{initiale}c^2 + \left(\Upsigma m_{initiale}c^2\right)^2 - T_S^2 - 2T_Sm_ac^2\\
       &= 2T_Sm_bc^2 + \left(\Upsigma m_{initiale}c^2\right)^2
     \end{align*}
   #+END_SRC

Finalement,
#+BEGIN_SRC latex
  \begin{align*}
   2T_Sm_bc^2 + \left(\Upsigma m_{initiale}c^2\right)^2 &= \left(\Upsigma m_{finale}c^2\right)^2\\
   2T_Sm_bc^2 &= \left(\Upsigma m_{finale}c^2\right)^2 - \left(\Upsigma m_{initiale}c^2\right)^2\\
   2T_Sm_bc^2 &= \left(\Upsigma m_{finale}c^2 - \Upsigma m_{initiale}c^2\right)\left(\Upsigma m_{finale}c^2 + \Upsigma m_{initiale}c^2\right)\\
   2T_Sm_bc^2 &= |Q|\cdot\left(\Upsigma m_{finale}c^2 + \Upsigma m_{initiale}c^2\right)
  \end{align*}
#+END_SRC

L'énergie cinétique minimum du faisceau incident est ainsi

$$T_S^{lab.} = \frac{|Q|\cdot\Upsigma m_{initiale,finale}c^2}{2\cdot
m_{cible}c^2} = T_S^{cdm}\cdot\frac{\Upsigma
m_{initiale,finale}c^2}{m_{cible}c^2}\geq T_S^{cdm}$$
** Accélérateurs
*** Introduction
- cyclotron :: Le cyclotron est un type d’accélérateur de particules circulaire
               inventé par Ernest Orlando Lawrence et Milton S. Livingston de
               l'université de Californie à Berkeley au début des
               années 1930. Dans un cyclotron, les particules placées dans un
               champ magnétique suivent une trajectoire en forme de spirale et
               sont accélérées par un champ électrique alternatif à des énergies
               de quelques MeV à une trentaine de MeV.
- synchrocyclotron :: Le cyclotron perd de son efficacité quand on cherche à
     accélérer des protons au-delà de 10 à 20 MeV, en raison de la variation
     relativiste de la masse qui perturbe le fonctionnement quand elle atteint
     une grandeur de 1 ou 2 %. Un synchrocyclotron est un cyclotron dont la
     fréquence du champ électrique est changée (progressivement diminuée) pour
     compenser le gain de masse des particules accélérées pendant que leur
     vitesse commence à approcher la vitesse de la lumière. Le synchrocyclotron
     permet d'atteindre des énergies de l'ordre de centaines de MeV. Le premier
     synchrocyclotron a été construit à l’Université de Californie (Berkeley)
     en 1946.
- synchrotron :: La caractéristique du synchrotron est que l'intensité du champ
                 magnétique de l'anneau est maintenue adaptée de façon synchrone
                 à l'énergie du faisceau de particules, afin de les maintenir
                 sur une trajectoire fixe. Il peut en outre y avoir un second
                 anneau, avec des particules tournant en sens inverse, afin de
                 réaliser des collisions entre particules avec une énergie
                 utilisable très élevée. Ce sont des collisionneurs.
*** Exercice

Proton de masse m = 938.27 MeV/c^{2} se déplaçant à la vitesse \vv{v} dans un
champ d'induction \vv{B} normal à \vv{v}.

1) PDF: $\Upsigma\vv{F} = m\vv{a} = \frac{d\vv{p}}{dt}$

   Régime relativiste m = \gamma{}m_{0} \rightarrow \vv{p} = \gamma{}m_{0}\vv{v}
   et donc d\vv{p}/dt = \gamma{}m_{0}d\vv{v}/dt. Or d\vv{v}/dt =
   R(d\theta/dt)^{2}\vv{u}_{r} = v^{2}/R\vv{u}_{r}. Soit

   $$\Upsigma\vv{F} = q\vv{v}\times\vv{B} = qvB\vv{u}_r$$
   $$qvB = \frac{\gamma{}m_{0}v^{2}}{R}$$
   $$R = \frac{\gamma{}mv}{qB} = \frac{p}{qB}$$

   À chaque tour, v\nearrow avec $\vv{B}=constante$ donc R\nearrow

2) Calcul de t_{0}

   $$\frac{d\theta}{dt} = \omega = \frac{v}{R} = \frac{qbR}{\gamma{}mR} =
   \frac{qB}{\gamma{}m}$$
   $$t_{0} = \frac{2\pi}{\omega} = \frac{2\pi}{qB}\cdot\gamma{}m$$

   Pour v\ll{}c, \gamma~1 et donc $$t_{0} = \frac{2\pi\,m}{qB}$$

3) B = 1.5T et R = 0.5m.

   #+BEGIN_SRC latex
     \begin{align*}
       p  &= qBR\\
       pc &= qRBc\\
       pc &= 0.5\cdot1.5\cdot3\,10^{8} = 225\,MeV
     \end{align*}
   #+END_SRC

   $$T = \frac{p^{2}}{2m} = \frac{p^{2}c^{2}}{2mc^{2}} =
   \frac{225^{2}}{2\cdot938.3} = 27\,MeV$$

   $$t_{0} = \frac{2\pi\,m}{qB} = \frac{2\pi\,mc^{2}}{qBc^{2}} = 44\,ns$$

4) $t = \frac{2\pi\gamma\,m}{qB}$ et $t_{0} = \frac{2\pi\,m}{qB}$

   $$\frac{t-t_{0}}{t_{0}}\ge5\%$$
   $$\frac{t_{lim.}}{t_{0}} = \gamma = 1.05$$
   $$T = (\gamma - 1)mc^{2} = 5\%\cdot938.3\,MeV = 47\,MeV$$

   Dans un cyclotron, dès lors que l'énergie par nucléon devient supérieure à
   ~50 MeV, des problèmes relativistes apparaissent /i.e./ la particule n'est
   plus accélérée en phase avec le champ électrique accélérateur \rightarrow
   *synchrocyclotron ou synchrotron*

5) La fréquence de rotation $f = \frac{v}{2\pi\,R} = \frac{qB}{2\pi\,m}$
   - synchrocyclotron :: on fait varier la fréquence f d'accélération pour
        compenser la variation de v
   - synchrotron :: on fait varier le champ magnétique B pour maintenir la
                    particule sur la même trajectoire /i.e./ le même rayon R

   T = 7 TeV et B = 5.4 T avec $R = \frac{\gamma\,mv}{qB} = \frac{pc}{qBc}$. Or
   #+BEGIN_SRC latex
     \begin{align*}
       (pc)^{2} &= E^{2} - m^{2}c^{4}\\
       &= T^{2} + m^{2}c^{4} + 2Tmc^{2} - m^{2}c^{4}\\
       &= T\cdot(T + 2mc^{2}) \sim T^{2}
     \end{align*}
   #+END_SRC
   d'où
   $$R = \frac{T}{qBc} =
   \frac{7\,10^{12}\cdot1.6\,10^{19}}{1.6\,10^{19}\cdot5.4\cdot3\,10^{8}} =
   4.3\,km$$
   soit une circonférence de 26 km.

6) p + p \rightarrow p + p + N^{+} + N^{-}

   T_{S} = |Q|/2 avec $Q = \Upsigma\,m_{initiale}c^{2} -
   \Upsigma\,m_{finale}c^{2}$ avec

   #+BEGIN_SRC latex
     \begin{align*}
       \Upsigma\,m_{initiale}c^{2} &= 2\,m_{p}c^{2}\\
       \Upsigma\,m_{finale}c^{2} &= 2\,m_{p}c^{2} + 2\,m_{N}c^{2}
     \end{align*}
   #+END_SRC

   $$T_{S} = \frac{2m_{N}c^{2}}{2} = m_{N}c^{2} = 7\,TeV$$

7) Réaction sur cible fixe

   #+BEGIN_SRC latex
     \begin{align*}
       T_{S} &= \frac{|Q|}{2}\cdot\frac{\Upsigma\,m_{if}c^{2}}{2m_{p}c^{2}}\\
       &= \frac{2m_{N}c^{2}}{2}\cdot\frac{4m_{p}c^{2}+2m_{N}c^{2}}{2m_{p}c^{2}}\\
       &\simeq\frac{(m_{N}c^{2})^{2}}{m_{p}c^{2}}\\
       &\simeq 50\,10^{6}\,GeV = 50\,PeV
     \end{align*}
   #+END_SRC

8) Rayon de courbure
$$R = \frac{pc}{qBc} \simeq \frac{T_{S}(eV)}{Bc} =
\frac{50\,PeV}{5.4\cdot3\,10^{8}} = 30\, 000\,km$$
